

spring.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/dbkiran?useSSL=false&serverTimezone=GMT&useLagacyDatetimeCode=false
spring.datasource.username=root
spring.datasource.password=pass1234

spring.jpa.show-sql=true

spring.main.allow-bean-definition-overriding=true
